## FIRST LINE/ROW: Info & Status
# First param â”€â”Œ
[username]
format = " [â•­â”€$user]($style)@"
style_user = "bold cyan"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) in "
style = "bold dimmed yellow"
ssh_only = false
disabled = false

# Third param
[directory]
style = "bold purple"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = ".../"
repo_root_style = "bold red"

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "white"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

# Prompt: param 2 â””â”€
[character]
success_symbol = " [â•°â”€](bold cyan)[Î»](bold green)"
error_symbol = " [â•°â”€](bold cyan)[Î»](bold red)"

[cmd_duration]
disabled = true

[git_branch]
symbol = ""
style = "bold red"

[nodejs]
symbol = "â¬¢ "
style = "bold green"

[python]
symbol = "ğŸ "
style = "bold blue"

[c]
style = "bold blue"

